name: Fourier pytest 

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  
      - name: Install dependencies
        run: |
             pip install --upgrade pip
             pip install -r requirements.txt
             pip install pandas==2.0.3

      - name: Run Pytest
        run: |
             pytest freq_unittest.py
             pytest high_freq_cleanup_unit_test.py
        
      - name: Upload Pytest log as artifact
        uses: actions/upload-artifact@v2
        with:
         name: Pytest Log
         path: pytest_output.log
